# Generated by Django 3.1.5 on 2021-01-04 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kimetsu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='名前')),
                ('sex', models.CharField(max_length=2, verbose_name='性別')),
                ('feature', models.CharField(max_length=100, verbose_name='特徴')),
            ],
        ),
    ]
